import {
  HeartPulse,
  Brain,
  ShieldCheck,
  Bone,
  Baby,
  HeartHandshake,
  Ambulance,
  ClipboardCheck,
  Stethoscope,
  ScanEye,
  Droplet,
  FlaskConical,
  Ear,
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  Menu,
  X,
  Search,
  User,
  Phone,
  Mail,
  MapPin,
  Clock,
  Calendar,
  ArrowRight,
  ExternalLink,
  Check,
  Star,
  Award,
  Globe,
  Language,
  Facebook,
  Twitter,
  Linkedin,
  Instagram,
  Youtube,
  ArrowUpRight,
  Download,
  Print,
  Share2,
  Eye,
  EyeOff,
  Loader2,
  AlertCircle,
  Info,
  Home,
  Building,
  BookOpen,
  Briefcase,
  Heart,
  Shield,
  Zap,
  Users,
  FlaskRound,
  Microscope,
  Pill,
  Syringe,
  Stethoscope as StethoscopeIcon,
  Thermometer,
  BloodDrop,
  Dna,
  Microscope as MicroscopeIcon,
  Activity,
  Waves,
  Pulse,
  Monitor,
  Camera,
  Image,
  FileText,
  FolderOpen,
  Settings,
  Bell,
  Notification,
  LogOut,
  LogIn,
  Key,
  Lock,
  Unlock,
  UserPlus,
  UserMinus,
  UserCheck,
  UserX,
  Plus,
  Minus,
  Edit,
  Trash2,
  Copy,
  Link,
  Unlink,
  Tag,
  Tags,
  Filter,
  SortAsc,
  SortDesc,
  Grid,
  List,
  Layout,
  Columns,
  Rows,
  Maximize,
  Minimize,
  Fullscreen,
  RotateCcw,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Move,
  Resize,
  Hand,
  Pointer,
  Select,
  Lasso,
  PenTool,
  Type,
  Text,
  Heading1,
  Heading2,
  Heading3,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Code,
  Code2,
  Terminal,
  Database,
  Server,
  HardDrive,
  Cpu,
  MemoryStick,
  Wifi,
  WifiOff,
  Bluetooth,
  BluetoothOff,
  Usb,
  Smartphone,
  Tablet,
  Laptop,
  Monitor as MonitorIcon,
  Printer,
  Scanner,
  Camera as CameraIcon,
  Video,
  Music,
  Film,
  Headphones,
  Mic,
  MicOff,
  Speaker,
  VolumeX,
  Volume1,
  Volume2,
  Power,
  RefreshCw,
  RefreshCcw,
  Sync,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudSun,
  CloudLightning,
  Sun,
  Moon,
  Star as StarIcon,
  CloudFog,
  Wind,
  Droplets,
  Umbrella,
  Thermometer as ThermometerIcon,
  Gauge,
  Target,
  TrendingUp,
  TrendingDown,
  BarChart,
  LineChart,
  PieChart,
  Activity as ActivityIcon,
  Heart as HeartIcon,
  Brain as BrainIcon,
  Lungs,
  Bone as BoneIcon,
  Pill as PillIcon,
  Syringe as SyringeIcon,
  Stethoscope as StethoscopeIcon2,
  Bandage,
  Scissors,
  Weight,
  Scale,
  FlaskRound as FlaskRoundIcon,
  TestTube,
  Microscope as MicroscopeIcon2,
  Dna as DnaIcon,
  Cells,
  Virus,
  Bacteria,
  Sprout,
  Leaf,
  TreePine,
  Flower,
  Seedling,
  Apple,
  HeartHandshake as HeartHandshakeIcon,
  Users as UsersIcon,
  User as UserIcon,
  UserCircle,
  UserPlus as UserPlusIcon,
  UserMinus as UserMinusIcon,
  UserCheck as UserCheckIcon,
  UserX as UserXIcon,
  Shield as ShieldIcon,
  ShieldCheck as ShieldCheckIcon,
  ShieldAlert,
  ShieldOff,
  Lock as LockIcon,
  Unlock as UnlockIcon,
  Key as KeyIcon,
  KeyRound,
  Fingerprint,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  ScanEye as ScanEyeIcon,
  ScanFace,
  ScanLine,
  ScanSearch,
  Search as SearchIcon,
  ZoomIn as ZoomInIcon,
  ZoomOut as ZoomOutIcon,
} from 'lucide-react';

export const icons = {
  // Medical
  heartPulse: HeartPulse,
  brain: Brain,
  shieldCheck: ShieldCheck,
  bone: Bone,
  baby: Baby,
  heartHandshake: HeartHandshake,
  ambulance: Ambulance,
  clipboardCheck: ClipboardCheck,
  stethoscope: Stethoscope,
  scanEye: ScanEye,
  droplet: Droplet,
  flaskConical: FlaskConical,
  ear: Ear,
  // UI
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  menu: Menu,
  x: X,
  search: Search,
  user: User,
  phone: Phone,
  mail: Mail,
  mapPin: MapPin,
  clock: Clock,
  calendar: Calendar,
  arrowRight: ArrowRight,
  externalLink: ExternalLink,
  check: Check,
  star: Star,
  award: Award,
  globe: Globe,
  language: Language,
  // Social
  facebook: Facebook,
  twitter: Twitter,
  linkedin: Linkedin,
  instagram: Instagram,
  youtube: Youtube,
  // Actions
  arrowUpRight: ArrowUpRight,
  download: Download,
  print: Print,
  share2: Share2,
  eye: Eye,
  eyeOff: EyeOff,
  loader: Loader2,
  alertCircle: AlertCircle,
  info: Info,
  // Layout
  home: Home,
  building: Building,
  bookOpen: BookOpen,
  briefcase: Briefcase,
  heart: Heart,
  shield: Shield,
  zap: Zap,
  users: Users,
  flaskRound: FlaskRound,
  microscope: Microscope,
  pill: Pill,
  syringe: Syringe,
  thermometer: Thermometer,
  bloodDrop: BloodDrop,
  dna: Dna,
  activity: Activity,
  waves: Waves,
  pulse: Pulse,
  monitor: Monitor,
  camera: Camera,
  image: Image,
  fileText: FileText,
  folderOpen: FolderOpen,
  settings: Settings,
  bell: Bell,
  notification: Notification,
  logOut: LogOut,
  logIn: LogIn,
  key: Key,
  lock: Lock,
  unlock: Unlock,
  userPlus: UserPlus,
  userMinus: UserMinus,
  userCheck: UserCheck,
  userX: UserX,
  plus: Plus,
  minus: Minus,
  edit: Edit,
  trash: Trash2,
  copy: Copy,
  link: Link,
  unlink: Unlink,
  tag: Tag,
  tags: Tags,
  filter: Filter,
  sortAsc: SortAsc,
  sortDesc: SortDesc,
  grid: Grid,
  list: List,
  layout: Layout,
  columns: Columns,
  rows: Rows,
  maximize: Maximize,
  minimize: Minimize,
  fullscreen: Fullscreen,
  rotateCcw: RotateCcw,
  rotateCw: RotateCw,
  flipHorizontal: FlipHorizontal,
  flipVertical: FlipVertical,
  crop: Crop,
  move: Move,
  resize: Resize,
  hand: Hand,
  pointer: Pointer,
  select: Select,
  lasso: Lasso,
  penTool: PenTool,
  type: Type,
  text: Text,
  heading1: Heading1,
  heading2: Heading2,
  heading3: Heading3,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strikethrough: Strikethrough,
  code: Code,
  code2: Code2,
  terminal: Terminal,
  database: Database,
  server: Server,
  hardDrive: HardDrive,
  cpu: Cpu,
  memoryStick: MemoryStick,
  wifi: Wifi,
  wifiOff: WifiOff,
  bluetooth: Bluetooth,
  bluetoothOff: BluetoothOff,
  usb: Usb,
  smartphone: Smartphone,
  tablet: Tablet,
  laptop: Laptop,
  monitor: MonitorIcon,
  printer: Printer,
  scanner: Scanner,
  camera: CameraIcon,
  video: Video,
  music: Music,
  film: Film,
  headphones: Headphones,
  mic: Mic,
  micOff: MicOff,
  speaker: Speaker,
  volumeX: VolumeX,
  volume1: Volume1,
  volume2: Volume2,
  power: Power,
  refreshCw: RefreshCw,
  refreshCcw: RefreshCcw,
  sync: Sync,
  cloud: Cloud,
  cloudRain: CloudRain,
  cloudSnow: CloudSnow,
  cloudSun: CloudSun,
  cloudLightning: CloudLightning,
  sun: Sun,
  moon: Moon,
  star: StarIcon,
  cloudFog: CloudFog,
  wind: Wind,
  droplets: Droplets,
  umbrella: Umbrella,
  thermometer: ThermometerIcon,
  gauge: Gauge,
  target: Target,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  barChart: BarChart,
  lineChart: LineChart,
  pieChart: PieChart,
  activity: ActivityIcon,
  heart: HeartIcon,
  brain: BrainIcon,
  lungs: Lungs,
  bone: BoneIcon,
  pill: PillIcon,
  syringe: SyringeIcon,
  stethoscope: StethoscopeIcon2,
  bandage: Bandage,
  scissors: Scissors,
  weight: Weight,
  scale: Scale,
  flaskRound: FlaskRoundIcon,
  testTube: TestTube,
  microscope: MicroscopeIcon2,
  dna: DnaIcon,
  cells: Cells,
  virus: Virus,
  bacteria: Bacteria,
  sprout: Sprout,
  leaf: Leaf,
  treePine: TreePine,
  flower: Flower,
  seedling: Seedling,
  apple: Apple,
  heartHandshake: HeartHandshakeIcon,
  users: UsersIcon,
  user: UserIcon,
  userCircle: UserCircle,
  userPlus: UserPlusIcon,
  userMinus: UserMinusIcon,
  userCheck: UserCheckIcon,
  userX: UserXIcon,
  shield: ShieldIcon,
  shieldCheck: ShieldCheckIcon,
  shieldAlert: ShieldAlert,
  shieldOff: ShieldOff,
  lock: LockIcon,
  unlock: UnlockIcon,
  key: KeyIcon,
  keyRound: KeyRound,
  fingerprint: Fingerprint,
  eye: EyeIcon,
  eyeOff: EyeOffIcon,
  scanEye: ScanEyeIcon,
  scanFace: ScanFace,
  scanLine: ScanLine,
  scanSearch: ScanSearch,
  search: SearchIcon,
  zoomIn: ZoomInIcon,
  zoomOut: ZoomOutIcon,
} as const;

export type IconName = keyof typeof icons;

export function Icon({ name, className = 'w-5 h-5', ...props }: { name: IconName; className?: string }) {
  const IconComponent = icons[name];
  if (!IconComponent) {
    console.warn(`Icon "${name}" not found`);
    return null;
  }
  return <IconComponent className={className} {...props} />;
}